# CodeRabbit Configuration File
# This file configures the AI code review settings for your project.

reviews:
  # Enable high-level summary of changes
  high_level_summary: true
  
  # Enable detailed walkthrough of changes
  poem: true
  
  # Provide focused feedback on the code
  review_status: true
  
  # Collapse walkthrough comments by default
  collapse_walkthrough: false
  
  # Auto-review all pull requests
  auto_review:
    enabled: true
    ignore_title_keywords:
      - "WIP"
      - "Draft"
    drafts: false

chat:
  # Enable chatting with the AI about the PR
  enabled: true

# Custom instructions for CodeRabbit AI
instructions: |
  You are reviewing a Next.js portfolio website using Sanity CMS and Tailwind CSS.
  
  Key Guidelines:
  1. Performance: Check for optimal image loading (next/image) and code splitting.
  2. Accessibility: Ensure semantic HTML and proper ARIA attributes.
  3. SEO: Verify meta tags and heading hierarchy.
  4. Styles: Prefer Tailwind utility classes over custom CSS.
  5. Security: Flag any exposed API keys or sensitive data.
  6. Sanity: Ensure schema definitions are type-safe.

# Files to ignore during review
path_filters:
  - "!dist/**"
  - "!node_modules/**"
  - "!.next/**"
  - "!package-lock.json"
  - "!yarn.lock"
  - "!.sanity/**"
